{
 "title": "March 2023 compared to reference",
 "time": { "from": "2023-03-02T00:00:00.000Z", "to": "2023-03-31T00:00:00.000Z" },
 "panels": [
  {
   "title": "Prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Fare amount median",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT fare_amount_quantile, \"timestamp\" FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of columns with drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Spearman corr. Fare amt vs trip dist",
   "type": "timeseries",
   "description": "spearman correlation value between fare amount and trip distance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", fare_amount_trip_dist_spearman_corr FROM metrics LIMIT 50 "
    }
   ]
  }
 ]
}