services:
  lambda:
    platform: linux/amd64
    build:
      context: .
    image: ${LOCAL_IMAGE_NAME}
    environment:
      - PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}
      - RUN_ID=a4b217a84e3a44ad870271b75331eb6c
      - MODEL_LOCATION=/app/model/model.pkl
      - KINESIS_ENDPOINT_URL=http://kinesis:4566/
      # needed for localstack to work with Docker compose in CI/CD environment
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=xyz
      - AWS_DEFAULT_REGION=us-west-2
    volumes:
      - ./integration-test/model:/app/model
      - ~/.aws:/root/.aws
    ports:
      - 8080:8080
  kinesis:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=kinesis
